// micro_app/react_app/src/App.js
import './App.css';
import { useContext, useState } from 'react';
import { Menu, Layout, Button, Space } from 'antd';
import { Link, Route } from 'react-router-dom';
import routerInfo from './router/index';
import { StoreContext } from './Context';

const { Header, Content } = Layout;
function App() {
  const store = useContext(StoreContext);
  const [state, setState ] = useState(store.getState());
  const handleGlobalStateChange = () => {
    store.dispatch({type: 'Save', payload:{ name: '786786', age: '1321513' }})
  }
  store.subscribe(()=>{
    setState(store.getState())
  })
  return (
    <Layout>
      <Space style={{ display: 'flex', justifyContent: 'center'}}>
        这里是全局变量: { Object.keys(state).map((item)=> item+':'+state[item]) }
        <Button onClick={handleGlobalStateChange}>修改全局变量</Button>
      </Space>
      <Menu mode="horizontal" theme="light" >
        <Menu.Item key="category"><Link to="/category">category</Link></Menu.Item>
        <Menu.Item key="detail"><Link to="/detail">detail</Link></Menu.Item>
        <Menu.Item key="display"><Link to="/display">display</Link></Menu.Item>
      </Menu>
      <Content>
        {
          routerInfo.map((item) => {
            return(
              <Route key={item.name} exact path={item.path} component={item.component}></Route>
            )
          })
        }
      </Content>
    </Layout>
  );
}

export default App;

// micro_app/vue_app/src/App.vue
<template>
  <div id="app">
    这里是全局变量: {{ state }}
    <el-button @click="handleGlobalStateChange">更改全局变量</el-button>
    <el-menu class="el-menu-demo" mode="horizontal">
      <el-menu-item index="display"><router-link to="/display">dispaly</router-link></el-menu-item>
      <el-menu-item index="category" ><router-link to="/category">category</router-link></el-menu-item>
      <el-menu-item index="detail"><router-link to="/detail">detail</router-link></el-menu-item>
    </el-menu>
    <router-view></router-view>
  </div>
</template>

<script>
export default {
  name: 'App',
  data() {
    return {
      state: null
    }
  },
  methods: {
    handleGlobalStateChange() {
      this.$store.dispatch({type: 'Save', payload: { age: '13546' }})
    }
  },
  mounted () {
    this.state = this.$store.getState();
    this.$store.subscribe(()=>{
      console.log("vue app", this.$store.getState())
      this.state = this.$store.getState()
    })
  },
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}
</style>
